import type { Metadata } from 'next';
import { GeistSans, GeistMono } from 'geist/font';
import './globals.css';
import { Toaster } from '../src/components/ui/toaster';
import { SidebarProvider } from '../src/context/SidebarProvider';

export const metadata: Metadata = {
  title: 'InvertFlow',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <SidebarProvider>
          {/* Removed Navbar from root layout */}
          {children}
          <Toaster />
        </SidebarProvider>
      </body>
    </html>
  );
}